

# Left Ethernet Chiplet - Left side
# Top to bottom
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_6/PAD}]      [get_pins -design [current_block] {tsv_array_17_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_5/PAD}]      [get_pins -design [current_block] {tsv_array_17_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_4/PAD}]      [get_pins -design [current_block] {tsv_array_17_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_3/PAD}]      [get_pins -design [current_block] {tsv_array_16_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_2/PAD}]      [get_pins -design [current_block] {tsv_array_16_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_1/PAD}]      [get_pins -design [current_block] {tsv_array_16_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_0/PAD}]      [get_pins -design [current_block] {tsv_array_15_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_2/PAD}]      [get_pins -design [current_block] {tsv_array_15_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_2/PAD}]      [get_pins -design [current_block] {tsv_array_15_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_CRS_DV/PAD}]    [get_pins -design [current_block] {tsv_array_14_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_MDIO/PAD}]      [get_pins -design [current_block] {tsv_array_14_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TX_EN/PAD}]     [get_pins -design [current_block] {tsv_array_14_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TXD1/PAD}]      [get_pins -design [current_block] {tsv_array_13_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TXD0/PAD}]      [get_pins -design [current_block] {tsv_array_13_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_RXD1/PAD}]      [get_pins -design [current_block] {tsv_array_13_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_1/PAD}]      [get_pins -design [current_block] {tsv_array_12_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_1/PAD}]      [get_pins -design [current_block] {tsv_array_12_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_RXD0/PAD}]      [get_pins -design [current_block] {tsv_array_12_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_REF_CLK/PAD}]   [get_pins -design [current_block] {tsv_array_11_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_MDC/PAD}]       [get_pins -design [current_block] {tsv_array_11_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_0/PAD}]      [get_pins -design [current_block] {tsv_array_11_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_0/PAD}]      [get_pins -design [current_block] {tsv_array_10_6/PAD}]

# Left Ethernet Chiplet - Bottom side
# Left to right
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_2/PAD}]  [get_pins -design [current_block] {tsv_array_10_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_B_1/PAD}]    [get_pins -design [current_block] {tsv_array_9_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_2/PAD}]    [get_pins -design [current_block] {tsv_array_10_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_2/PAD}]  [get_pins -design [current_block] {tsv_array_9_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_0/PAD}]    [get_pins -design [current_block] {tsv_array_8_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_nCS/PAD}]   [get_pins -design [current_block] {tsv_array_10_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_SCLK/PAD}]  [get_pins -design [current_block] {tsv_array_9_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_3/PAD}]  [get_pins -design [current_block] {tsv_array_8_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_1/PAD}]  [get_pins -design [current_block] {tsv_array_10_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_1/PAD}]  [get_pins -design [current_block] {tsv_array_9_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_2/PAD}]  [get_pins -design [current_block] {tsv_array_8_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_1/PAD}]  [get_pins -design [current_block] {tsv_array_10_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_0/PAD}]  [get_pins -design [current_block] {tsv_array_9_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_B_0/PAD}]    [get_pins -design [current_block] {tsv_array_8_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_1/PAD}]    [get_pins -design [current_block] {tsv_array_10_12/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_0/PAD}]  [get_pins -design [current_block] {tsv_array_9_12/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_0/PAD}]  [get_pins -design [current_block] {tsv_array_8_12/PAD}]

# Left Ethernet Chiplet - Top side
# Left to right

connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_2/PAD}]  [get_pins -design [current_block] {tsv_array_18_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_2/PAD}]    [get_pins -design [current_block] {tsv_array_18_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_1/PAD}]  [get_pins -design [current_block] {tsv_array_19_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_0/PAD}]  [get_pins -design [current_block] {tsv_array_20_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_2/PAD}]  [get_pins -design [current_block] {tsv_array_19_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_1/PAD}]  [get_pins -design [current_block] {tsv_array_20_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_T_1/PAD}]    [get_pins -design [current_block] {tsv_array_19_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SWDIO_IO/PAD}]   [get_pins -design [current_block] {tsv_array_18_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_1/PAD}]    [get_pins -design [current_block] {tsv_array_20_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SE_I/PAD}]       [get_pins -design [current_block] {tsv_array_19_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_TEST_I/PAD}]     [get_pins -design [current_block] {tsv_array_18_10/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_CLK_I/PAD}]      [get_pins -design [current_block] {tsv_array_20_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SWDCK_I/PAD}]    [get_pins -design [current_block] {tsv_array_19_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_NRST_I/PAD}]     [get_pins -design [current_block] {tsv_array_18_11/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_T_0/PAD}]    [get_pins -design [current_block] {tsv_array_20_12/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_0/PAD}]    [get_pins -design [current_block] {tsv_array_19_12/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_0/PAD}]  [get_pins -design [current_block] {tsv_array_18_12/PAD}]



# Right Ethernet Chiplet - Right side
# Top to bottom
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_0/PAD}]      [get_pins -design [current_block] {tsv_array_17_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_0/PAD}]      [get_pins -design [current_block] {tsv_array_17_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_MDC/PAD}]       [get_pins -design [current_block] {tsv_array_17_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_REF_CLK/PAD}]   [get_pins -design [current_block] {tsv_array_16_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_RXD0/PAD}]      [get_pins -design [current_block] {tsv_array_16_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_1/PAD}]      [get_pins -design [current_block] {tsv_array_16_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_1/PAD}]      [get_pins -design [current_block] {tsv_array_15_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_RXD1/PAD}]      [get_pins -design [current_block] {tsv_array_15_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TXD0/PAD}]      [get_pins -design [current_block] {tsv_array_15_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TXD1/PAD}]      [get_pins -design [current_block] {tsv_array_14_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TX_EN/PAD}]     [get_pins -design [current_block] {tsv_array_14_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_MDIO/PAD}]      [get_pins -design [current_block] {tsv_array_14_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_CRS_DV/PAD}]    [get_pins -design [current_block] {tsv_array_13_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_2/PAD}]      [get_pins -design [current_block] {tsv_array_13_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_2/PAD}]      [get_pins -design [current_block] {tsv_array_13_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_0/PAD}]      [get_pins -design [current_block] {tsv_array_12_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_1/PAD}]      [get_pins -design [current_block] {tsv_array_12_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_2/PAD}]      [get_pins -design [current_block] {tsv_array_12_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_3/PAD}]      [get_pins -design [current_block] {tsv_array_11_24/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_4/PAD}]      [get_pins -design [current_block] {tsv_array_11_23/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_5/PAD}]      [get_pins -design [current_block] {tsv_array_11_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_6/PAD}]      [get_pins -design [current_block] {tsv_array_10_24/PAD}]

# Right Ethernet Chiplet - Top side
# Left to right
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_0/PAD}]  [get_pins -design [current_block] {tsv_array_21_17/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_0/PAD}]  [get_pins -design [current_block] {tsv_array_21_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_1/PAD}]    [get_pins -design [current_block] {tsv_array_20_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_B_0/PAD}]    [get_pins -design [current_block] {tsv_array_19_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_0/PAD}]  [get_pins -design [current_block] {tsv_array_18_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_1/PAD}]  [get_pins -design [current_block] {tsv_array_20_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_2/PAD}]  [get_pins -design [current_block] {tsv_array_19_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_1/PAD}]  [get_pins -design [current_block] {tsv_array_18_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_1/PAD}]  [get_pins -design [current_block] {tsv_array_20_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_3/PAD}]  [get_pins -design [current_block] {tsv_array_19_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_SCLK/PAD}]  [get_pins -design [current_block] {tsv_array_18_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_nCS/PAD}]   [get_pins -design [current_block] {tsv_array_20_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_0/PAD}]    [get_pins -design [current_block] {tsv_array_19_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_2/PAD}]  [get_pins -design [current_block] {tsv_array_18_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_2/PAD}]    [get_pins -design [current_block] {tsv_array_19_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_B_1/PAD}]    [get_pins -design [current_block] {tsv_array_18_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_2/PAD}]  [get_pins -design [current_block] {tsv_array_18_23/PAD}]

# Right Ethernet Chiplet - Bottom side
# Left to right

connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_0/PAD}]  [get_pins -design [current_block] {tsv_array_10_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_0/PAD}]    [get_pins -design [current_block] {tsv_array_9_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_T_0/PAD}]    [get_pins -design [current_block] {tsv_array_8_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_NRST_I/PAD}]     [get_pins -design [current_block] {tsv_array_7_18/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SWDCK_I/PAD}]    [get_pins -design [current_block] {tsv_array_10_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_CLK_I/PAD}]      [get_pins -design [current_block] {tsv_array_9_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_TEST_I/PAD}]     [get_pins -design [current_block] {tsv_array_8_19/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SE_I/PAD}]       [get_pins -design [current_block] {tsv_array_10_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_1/PAD}]    [get_pins -design [current_block] {tsv_array_9_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SWDIO_IO/PAD}]   [get_pins -design [current_block] {tsv_array_8_20/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_T_1/PAD}]    [get_pins -design [current_block] {tsv_array_10_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_1/PAD}]  [get_pins -design [current_block] {tsv_array_9_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_2/PAD}]  [get_pins -design [current_block] {tsv_array_8_21/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_0/PAD}]  [get_pins -design [current_block] {tsv_array_10_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_1/PAD}]  [get_pins -design [current_block] {tsv_array_9_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_2/PAD}]    [get_pins -design [current_block] {tsv_array_8_22/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_2/PAD}]  [get_pins -design [current_block] {tsv_array_10_23/PAD}]



# Compute chiplet top
# left to right
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_B_0/PAD} ]  [get_pins -design [current_block] {tsv_array_21_12/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_B_0/PAD} ]  [get_pins -design [current_block] {tsv_array_18_13/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_P1_00/PAD} ]      [get_pins -design [current_block] {tsv_array_19_13/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_B_0/PAD} ]    [get_pins -design [current_block] {tsv_array_20_13/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSS_B_0/PAD} ]    [get_pins -design [current_block] {tsv_array_21_13/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_P1_01/PAD} ]      [get_pins -design [current_block] {tsv_array_18_14/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_B_1/PAD} ]  [get_pins -design [current_block] {tsv_array_19_14/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_B_1/PAD} ]  [get_pins -design [current_block] {tsv_array_20_14/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_P1_03/PAD} ]      [get_pins -design [current_block] {tsv_array_21_14/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_B_1/PAD} ]    [get_pins -design [current_block] {tsv_array_18_15/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSS_B_1/PAD} ]    [get_pins -design [current_block] {tsv_array_19_15/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_NRST_I/PAD} ]     [get_pins -design [current_block] {tsv_array_20_15/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_B_2/PAD} ]  [get_pins -design [current_block] {tsv_array_21_15/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_B_2/PAD} ]  [get_pins -design [current_block] {tsv_array_18_16/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_P1_04/PAD} ]      [get_pins -design [current_block] {tsv_array_19_16/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_P1_05/PAD} ]      [get_pins -design [current_block] {tsv_array_20_16/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_B_2/PAD} ]    [get_pins -design [current_block] {tsv_array_21_16/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_STRAP_I/PAD} ]    [get_pins -design [current_block] {tsv_array_18_17/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_SE_I/PAD} ]       [get_pins -design [current_block] {tsv_array_19_17/PAD}]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_TEST_I/PAD} ]     [get_pins -design [current_block] {tsv_array_20_17/PAD}]

# Compute chiplet Bottom
# left to right
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_T_0/PAD} ]  [get_pins -design [current_block] {tsv_array_10_13/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_T_0/PAD} ]  [get_pins -design [current_block] {tsv_array_9_13/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_SWDCK_I/PAD} ]    [get_pins -design [current_block] {tsv_array_8_13/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_T_0/PAD} ]    [get_pins -design [current_block] {tsv_array_7_13/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSS_T_0/PAD} ]    [get_pins -design [current_block] {tsv_array_10_14/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_SWDIO_IO/PAD} ]   [get_pins -design [current_block] {tsv_array_9_14/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_CLK_I/PAD} ]      [get_pins -design [current_block] {tsv_array_8_14/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_SCLK/PAD} ]  [get_pins -design [current_block] {tsv_array_7_14/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_T_1/PAD} ]  [get_pins -design [current_block] {tsv_array_10_15/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_T_1/PAD} ]  [get_pins -design [current_block] {tsv_array_9_15/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_IO_0/PAD} ]  [get_pins -design [current_block] {tsv_array_8_15/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_IO_1/PAD} ]  [get_pins -design [current_block] {tsv_array_7_15/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_T_1/PAD} ]    [get_pins -design [current_block] {tsv_array_10_16/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSS_T_1/PAD} ]    [get_pins -design [current_block] {tsv_array_9_16/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_IO_2/PAD} ]  [get_pins -design [current_block] {tsv_array_8_16/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_IO_3/PAD} ]  [get_pins -design [current_block] {tsv_array_7_16/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_QSPI_nCS/PAD} ]   [get_pins -design [current_block] {tsv_array_10_17/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDDIO_T_2/PAD} ]  [get_pins -design [current_block] {tsv_array_9_17/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VDD_T_2/PAD} ]    [get_pins -design [current_block] {tsv_array_8_17/PAD} ]
connect_pins -driver [get_pins -design [current_block] {cmp_BuPAD_VSSIO_T_2/PAD} ]  [get_pins -design [current_block] {tsv_array_7_17/PAD} ]