

# Left Ethernet Chiplet - Left side
# Top to bottom
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_6/PAD}]      [get_pins -design [current_block] {wb_array_28_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_5/PAD}]      [get_pins -design [current_block] {wb_array_27_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_4/PAD}]      [get_pins -design [current_block] {wb_array_26_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_3/PAD}]      [get_pins -design [current_block] {wb_array_25_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_2/PAD}]      [get_pins -design [current_block] {wb_array_24_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_1/PAD}]      [get_pins -design [current_block] {wb_array_23_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_HOST_IO_0/PAD}]      [get_pins -design [current_block] {wb_array_22_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_2/PAD}]      [get_pins -design [current_block] {wb_array_21_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_2/PAD}]      [get_pins -design [current_block] {wb_array_20_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_CRS_DV/PAD}]    [get_pins -design [current_block] {wb_array_19_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_MDIO/PAD}]      [get_pins -design [current_block] {wb_array_18_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TX_EN/PAD}]     [get_pins -design [current_block] {wb_array_17_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TXD1/PAD}]      [get_pins -design [current_block] {wb_array_16_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_TXD0/PAD}]      [get_pins -design [current_block] {wb_array_15_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_RXD1/PAD}]      [get_pins -design [current_block] {wb_array_14_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_1/PAD}]      [get_pins -design [current_block] {wb_array_13_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_1/PAD}]      [get_pins -design [current_block] {wb_array_12_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_RXD0/PAD}]      [get_pins -design [current_block] {wb_array_11_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_REF_CLK/PAD}]   [get_pins -design [current_block] {wb_array_10_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_RMII_MDC/PAD}]       [get_pins -design [current_block] {wb_array_9_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_R_0/PAD}]      [get_pins -design [current_block] {wb_array_8_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_R_0/PAD}]      [get_pins -design [current_block] {wb_array_7_0/PAD}]

# Left Ethernet Chiplet - Bottom side
# Left to right
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_2/PAD}]  [get_pins -design [current_block] {wb_array_6_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_B_1/PAD}]    [get_pins -design [current_block] {wb_array_5_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_2/PAD}]    [get_pins -design [current_block] {wb_array_4_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_2/PAD}]  [get_pins -design [current_block] {wb_array_3_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_0/PAD}]    [get_pins -design [current_block] {wb_array_2_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_nCS/PAD}]   [get_pins -design [current_block] {wb_array_1_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_SCLK/PAD}]  [get_pins -design [current_block] {wb_array_0_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_3/PAD}]  [get_pins -design [current_block] {wb_array_0_1/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_1/PAD}]  [get_pins -design [current_block] {wb_array_0_2/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_1/PAD}]  [get_pins -design [current_block] {wb_array_0_3/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_2/PAD}]  [get_pins -design [current_block] {wb_array_0_4/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_1/PAD}]  [get_pins -design [current_block] {wb_array_0_5/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_QSPI_IO_0/PAD}]  [get_pins -design [current_block] {wb_array_0_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_B_0/PAD}]    [get_pins -design [current_block] {wb_array_0_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_B_1/PAD}]    [get_pins -design [current_block] {wb_array_0_8/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_B_0/PAD}]  [get_pins -design [current_block] {wb_array_0_9/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_B_0/PAD}]  [get_pins -design [current_block] {wb_array_0_10/PAD}]

# Left Ethernet Chiplet - Top side
# Left to right

connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_2/PAD}]  [get_pins -design [current_block] {wb_array_27_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_2/PAD}]    [get_pins -design [current_block] {wb_array_28_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_1/PAD}]  [get_pins -design [current_block] {wb_array_29_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSSIO_T_0/PAD}]  [get_pins -design [current_block] {wb_array_30_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_2/PAD}]  [get_pins -design [current_block] {wb_array_31_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_1/PAD}]  [get_pins -design [current_block] {wb_array_32_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_T_1/PAD}]    [get_pins -design [current_block] {wb_array_33_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SWDIO_IO/PAD}]   [get_pins -design [current_block] {wb_array_34_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_1/PAD}]    [get_pins -design [current_block] {wb_array_35_0/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SE_I/PAD}]       [get_pins -design [current_block] {wb_array_35_1/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_TEST_I/PAD}]     [get_pins -design [current_block] {wb_array_35_2/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_CLK_I/PAD}]      [get_pins -design [current_block] {wb_array_35_3/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_SWDCK_I/PAD}]    [get_pins -design [current_block] {wb_array_35_4/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_NRST_I/PAD}]     [get_pins -design [current_block] {wb_array_35_5/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VSS_T_0/PAD}]    [get_pins -design [current_block] {wb_array_35_6/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDD_T_0/PAD}]    [get_pins -design [current_block] {wb_array_35_7/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth1_BuPAD_VDDIO_T_0/PAD}]  [get_pins -design [current_block] {wb_array_35_8/PAD}]



# Right Ethernet Chiplet - Right side
# Top to bottom
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_0/PAD}]      [get_pins -design [current_block] {wb_array_28_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_0/PAD}]      [get_pins -design [current_block] {wb_array_27_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_MDC/PAD}]       [get_pins -design [current_block] {wb_array_26_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_REF_CLK/PAD}]   [get_pins -design [current_block] {wb_array_25_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_RXD0/PAD}]      [get_pins -design [current_block] {wb_array_24_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_1/PAD}]      [get_pins -design [current_block] {wb_array_23_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_1/PAD}]      [get_pins -design [current_block] {wb_array_22_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_RXD1/PAD}]      [get_pins -design [current_block] {wb_array_21_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TXD0/PAD}]      [get_pins -design [current_block] {wb_array_20_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TXD1/PAD}]      [get_pins -design [current_block] {wb_array_19_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_TX_EN/PAD}]     [get_pins -design [current_block] {wb_array_18_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_MDIO/PAD}]      [get_pins -design [current_block] {wb_array_17_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_RMII_CRS_DV/PAD}]    [get_pins -design [current_block] {wb_array_16_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_R_2/PAD}]      [get_pins -design [current_block] {wb_array_15_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_R_2/PAD}]      [get_pins -design [current_block] {wb_array_14_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_0/PAD}]      [get_pins -design [current_block] {wb_array_13_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_1/PAD}]      [get_pins -design [current_block] {wb_array_12_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_2/PAD}]      [get_pins -design [current_block] {wb_array_11_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_3/PAD}]      [get_pins -design [current_block] {wb_array_10_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_4/PAD}]      [get_pins -design [current_block] {wb_array_9_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_5/PAD}]      [get_pins -design [current_block] {wb_array_8_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_HOST_IO_6/PAD}]      [get_pins -design [current_block] {wb_array_7_35/PAD}]

# Right Ethernet Chiplet - Top side
# Left to right
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_0/PAD}]  [get_pins -design [current_block] {wb_array_35_25/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_0/PAD}]  [get_pins -design [current_block] {wb_array_35_26/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_1/PAD}]    [get_pins -design [current_block] {wb_array_35_27/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_B_0/PAD}]    [get_pins -design [current_block] {wb_array_35_28/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_0/PAD}]  [get_pins -design [current_block] {wb_array_35_29/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_1/PAD}]  [get_pins -design [current_block] {wb_array_35_30/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_2/PAD}]  [get_pins -design [current_block] {wb_array_35_31/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_1/PAD}]  [get_pins -design [current_block] {wb_array_35_32/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_1/PAD}]  [get_pins -design [current_block] {wb_array_35_33/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_IO_3/PAD}]  [get_pins -design [current_block] {wb_array_35_34/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_SCLK/PAD}]  [get_pins -design [current_block] {wb_array_35_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_QSPI_nCS/PAD}]   [get_pins -design [current_block] {wb_array_34_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_0/PAD}]    [get_pins -design [current_block] {wb_array_33_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_B_2/PAD}]  [get_pins -design [current_block] {wb_array_32_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_B_2/PAD}]    [get_pins -design [current_block] {wb_array_31_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_B_1/PAD}]    [get_pins -design [current_block] {wb_array_30_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_B_2/PAD}]  [get_pins -design [current_block] {wb_array_29_35/PAD}]

# Right Ethernet Chiplet - Bottom side
# Left to right

connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_0/PAD}]  [get_pins -design [current_block] {wb_array_0_25/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_0/PAD}]    [get_pins -design [current_block] {wb_array_0_26/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_T_0/PAD}]    [get_pins -design [current_block] {wb_array_0_27/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_NRST_I/PAD}]     [get_pins -design [current_block] {wb_array_0_28/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SWDCK_I/PAD}]    [get_pins -design [current_block] {wb_array_0_29/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_CLK_I/PAD}]      [get_pins -design [current_block] {wb_array_0_30/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_TEST_I/PAD}]     [get_pins -design [current_block] {wb_array_0_31/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SE_I/PAD}]       [get_pins -design [current_block] {wb_array_0_32/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_1/PAD}]    [get_pins -design [current_block] {wb_array_0_33/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_SWDIO_IO/PAD}]   [get_pins -design [current_block] {wb_array_0_34/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSS_T_1/PAD}]    [get_pins -design [current_block] {wb_array_0_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_1/PAD}]  [get_pins -design [current_block] {wb_array_1_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDDIO_T_2/PAD}]  [get_pins -design [current_block] {wb_array_2_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_0/PAD}]  [get_pins -design [current_block] {wb_array_3_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_1/PAD}]  [get_pins -design [current_block] {wb_array_4_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VDD_T_2/PAD}]    [get_pins -design [current_block] {wb_array_5_35/PAD}]
connect_pins -driver [get_pins -design [current_block] {eth0_BuPAD_VSSIO_T_2/PAD}]  [get_pins -design [current_block] {wb_array_6_35/PAD}]
